"""
Weekly Research Digest
======================
Fetches recent papers on online research methods, public opinion & polling,
and survey methodology from preprint servers and journals, summarises them
with Claude, and emails you a digest.

SETUP (one-time):
  pip install anthropic feedparser requests pyyaml

CONFIGURATION:
  Feeds and prompt wording live in config.yaml, colocated with this
  script — edit that file to add/remove feeds or tweak the prompt,
  no code changes needed.

TO AUTOMATE (run every Monday morning):
  - Mac/Linux: cron job  →  0 8 * * 1 python /path/to/weekly_digest.py
  - Anywhere:  GitHub Actions (free) — see comment at the bottom
"""

import os
import smtplib
import feedparser
import anthropic
import yaml
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timedelta, timezone

# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
EMAIL_FROM        = os.environ.get("EMAIL_FROM")
EMAIL_TO          = os.environ.get("EMAIL_TO")
EMAIL_PASS        = os.environ.get("EMAIL_PASS")

CONFIG_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.yaml")
with open(CONFIG_PATH, "r") as f:
    CONFIG = yaml.safe_load(f)

# ─────────────────────────────────────────────
# SOURCES
# ─────────────────────────────────────────────

ALL_FEEDS = CONFIG["feeds"]

MAX_PER_FEED  = 10
DAYS_LOOKBACK = 30

# ─────────────────────────────────────────────
# FETCH PAPERS
# ─────────────────────────────────────────────

def fetch_papers(feeds, days=30, limit=10):
    papers = []
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)

    for url in feeds:
        try:
            feed = feedparser.parse(url)
            count = 0
            for entry in feed.entries:
                if count >= limit:
                    break
                published = None
                if hasattr(entry, "published_parsed") and entry.published_parsed:
                    published = datetime(*entry.published_parsed[:6], tzinfo=timezone.utc)
                if published and published < cutoff:
                    continue
                papers.append({
                    "title":   entry.get("title", "No title").strip(),
                    "summary": entry.get("summary", entry.get("description", ""))[:600],
                    "link":    entry.get("link", ""),
                    "source":  feed.feed.get("title", url),
                    "date":    published.strftime("%d %b %Y") if published else "Unknown",
                })
                count += 1
        except Exception as e:
            print(f"⚠️  Could not fetch {url}: {e}")

    return papers

# ─────────────────────────────────────────────
# SUMMARISE WITH CLAUDE
# ─────────────────────────────────────────────

def summarise_papers(papers, api_key, researcher_profile, instructions):
    if not papers:
        return "<p>No new papers found this week.</p>"

    client = anthropic.Anthropic(api_key=api_key)

    paper_text = ""
    for i, p in enumerate(papers, 1):
        paper_text += f"\n[{i}] {p['title']}\nSource: {p['source']} | {p['date']}\nURL: {p['link']}\nAbstract: {p['summary']}\n"

    prompt = f"""You are a research curator for a researcher working across the following areas:

{researcher_profile.strip()}

From the {len(papers)} papers below, please:
{instructions.strip()}

Papers:
{paper_text}

Return only the HTML content (no <html> or <body> tags), no markdown.
"""

    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )

    return message.content[0].text

# ─────────────────────────────────────────────
# BUILD & SEND EMAIL
# ─────────────────────────────────────────────

def send_email(html_body, from_addr, to_addr, password):
    week = datetime.now().strftime("%d %b %Y")
    subject = f"📚 Weekly Research Digest — {week}"

    full_html = f"""
    <html><body style="font-family: Georgia, serif; max-width: 680px; margin: 0 auto; color: #222;">
      <div style="background:#1a3a5c; color:white; padding:20px 30px; border-radius:6px 6px 0 0;">
        <h1 style="margin:0; font-size:22px;">📚 Weekly Research Digest</h1>
        <p style="margin:4px 0 0; opacity:0.8; font-size:14px;">Week of {week} · Online Methods, Polling & Survey Research</p>
      </div>
      <div style="padding:24px 30px; background:#fafafa; border:1px solid #ddd; border-top:none; border-radius:0 0 6px 6px;">
        {html_body}
      </div>
      <p style="font-size:12px; color:#999; text-align:center; margin-top:16px;">
        Generated by your weekly_digest.py script · <a href="https://console.anthropic.com">Anthropic Console</a>
      </p>
    </body></html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = from_addr
    msg["To"]      = to_addr
    msg.attach(MIMEText(full_html, "html"))

    # Strip stray whitespace (including non-breaking spaces sometimes picked up
    # when copy-pasting an App Password) that smtplib can't base64-encode.
    password = "".join(password.split())

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(from_addr, password)
        server.sendmail(from_addr, to_addr, msg.as_string())

    print(f"✅ Digest sent to {to_addr}")

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("🔍 Fetching papers...")
    papers = fetch_papers(ALL_FEEDS, days=DAYS_LOOKBACK, limit=MAX_PER_FEED)
    print(f"   Found {len(papers)} items")

    print("🤖 Summarising with Claude...")
    digest_html = summarise_papers(
        papers,
        ANTHROPIC_API_KEY,
        CONFIG["researcher_profile"],
        CONFIG["instructions"],
    )

    print("📧 Sending email...")
    send_email(digest_html, EMAIL_FROM, EMAIL_TO, EMAIL_PASS)


# ─────────────────────────────────────────────
# GITHUB ACTIONS AUTOMATION (optional)
# ─────────────────────────────────────────────
#
# Runs every Monday at 8am UTC for free — no computer needed.
#
# 1. Push this file to a GitHub repo
# 2. Create .github/workflows/digest.yml containing:
#
# name: Weekly Digest
# on:
#   schedule:
#     - cron: '0 8 * * 1'
#   workflow_dispatch:
# jobs:
#   run-digest:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with: { python-version: '3.11' }
#       - run: pip install anthropic feedparser requests pyyaml
#       - run: python weekly_digest.py
#         env:
#           ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
#           EMAIL_FROM:        ${{ secrets.EMAIL_FROM }}
#           EMAIL_TO:          ${{ secrets.EMAIL_TO }}
#           EMAIL_PASS:        ${{ secrets.EMAIL_PASS }}
#
# 3. Add your secrets under repo Settings → Secrets and variables → Actions
